---
spring:
  name: prod-YAML
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/online_store
    username: root
    password: root
  driver-class-name: com.mysql.cj.jdbc.Driver8